spring:
  application:
    name: expense-control-backend
  datasource:
    database: expense_control
    url: jdbc:postgresql://localhost:5432/expense_control
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
